from pathlib import Path
import json,csv,hashlib,datetime,shutil,sys,subprocess
R=Path(r'C:\Users\Hngk\Documents\Codex'); C=R/'PUMA_STAGE2_PROMPT6/PUMA_STAGE2_PROMPT6_CODE'; P=R/'PUMA_STAGE2_PROMPT6/DATA_PRESELECTION'; O=R/'2026-09-07/use-the-autoresearch-skill-x20-https/outputs/PUMA_STAGE2_RESEARCH_PROMPTS_1_TO_4/EXPLORATION_6'
sys.path.insert(0,str(C/'src'))
from puma_exploration6.config import ExperimentConfig
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def save(p,x):(O/p).write_text(json.dumps(x,indent=2),encoding='utf-8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
protocol=dict(registered_utc=now,stage_order=list('ABCDEFGHIJ'),research_training_started=False,primary='DEV fixed-ten ROI Macro-F1; semantic macro-F1 and per-class harm secondary, never conflate subset and complete-proposal evaluation',grouping='ROI',seeds=[17,29,43],promotion=dict(mean_paired_roi_delta_min=0.003,positive_seeds_min=2,roi_paired_bootstrap_samples=2000,bootstrap_seed=1706,confidence=0.95,lower_confidence_bound_min=0,max_mean_class_recall_loss=0.10,max_generalization_gap_increase=0.05,complexity_tie_break='smaller model, then unchanged historical recipe'),data_scaling=dict(sizes=[300,600,900],epochs=10,selection='fixed_final',LR=0.001,WD=0.01,batch=64,sampler='inverse',loss='CE',rank=8,scheduler='constant',comparison='common DEV; three matched seeds; no endpoint retuning'),augmentation=dict(arms=['AUG0 no augmentation raw parity','AUG1 geometry','AUG2 geometry+fixed H/E OD stain'],seeds=[17,29,43],epochs=10,control='matched effective batch64, fixed final10; physical batch1 accumulation64 on CPU if memory requires',jitter='GATED: no run unless empirical displacement distribution is verified and a distribution is preregistered'),longtail=dict(arms=['inverse CE','natural CE','tempered alpha0.5 CE','cRT reset W/R freeze Ph/Pb'],prior_correction='not reopened absent distinct evidence; no stacking'),hpo=dict(location='TRAIN only, 3 group-disjoint folds',trial_count_optimizer=12,trial_count_regularization=9,max_finalists=2,search='shipped seeded bounded config generator, no conversational per-trial retuning',seed=1706,finalist_rule='mean CV ROI-F1, class guard against matched control; ties prefer fewer parameters; at most two DEV finalists',maximum_epochs=20,patience=5),tier_a=dict(arms=['on','off'],confounding='TRAIN-only ROI/class descriptive association; held-group incremental utility decides retention'),representation=dict(arms=['cls','gaussian sigma1.5','neighborhood radius1','exact fixed global-local'],settings='matched stabilized training settings; no retuning pooling',scalar_mix='not run by default'),adaptation=dict(gate='All specified Exploration6 G requirements; residual nonseparability must survive prior interventions',prior_exact_lora='prohibited unchanged rerun'),final=dict(three_seed=[17,29,43],checkpoint_for_single_model='seed17 fixed prospectively, not best seed; no ensemble',confirmation='one event after full recipe freeze',natural='one event after full recipe freeze; no class balancing; absent class recall/support-F1 not estimable; official fixed metrics separately',V17='complete fixed Stage1 proposal population where feasible; verify upstream history separately'),stopping='No further architecture search after gated stages and reporting. Insufficient evidence retains prior model. CPU cost does not justify substituting cached finite augmentations for on-the-fly augmentation.')
save('RESEARCH_STATE/PREREGISTERED_PROTOCOL.json',protocol)
configs=[]
base=json.loads((C/'configs/00_historical_A5_cached.json').read_text())
for n in [300,600,900]:
    d=json.loads(json.dumps(base));d.update(experiment_id=f'p6_A_D{n}',manifest=str(P/f'SELECTION/D{n}.csv'),output_dir=str(O/'EXPERIMENTS'),cached_features=str(P/f'D{n}_cls.npy'),tier_a=str(P/f'D{n}_tierA.npy'),device='cpu')
    cfg=ExperimentConfig.from_dict(d)
    p=O/f'CONFIGS_RESOLVED/A_D{n}_base.json';p.write_text(json.dumps(cfg.to_dict(),indent=2),encoding='utf-8');configs.append(str(p))
save('CONFIGS_RESOLVED/DATA_SCALING_BASES.json',dict(configs=configs,status='WAITING_FOR_VERIFIED_CACHES'))
evidence=[
['augmentation','1-5','on-the-fly augmentation for A5','C_PROPOSED_NOT_VALIDATED','Historical cached features do not test on-the-fly augmentation','yes','Raw-image matched no-augmentation control'],
['global-local','4','LN((LN(CLS)+LN(Gaussian sigma1.5))/2)','B_POSITIVE_UNCONFIRMED','Internal gain did not establish independent confirmation','yes','Fresh prospective matched replication'],
['regularization','2-5','AdamW WD0.01; fixed epoch10','D_PARTIALLY_TESTED','Systematic bounded HPO not completed','yes','TRAIN-only grouped HPO'],
['long-tail','2-5','CE/LA/inverse-count replacement','D_PARTIALLY_TESTED','cRT remains distinct from joint-prior experiments','yes','Tempered exposure/cRT mechanism'],
['encoder adaptation','4','QV r8 alpha16 last4 five epochs; adapterLR1e-5 headLR1e-3','A_NEGATIVE_EXECUTED','Finite-budget null; not proof all adaptation fails','conditional','Materially different adaptation only after gate'],
['data scaling','6','D300 subset D600 subset D900','E_UNSTUDIED','New manifests now admitted under explicit historical-exposure amendment','yes','Matched seed fixed-final causal control']]
with (O/'RESEARCH_STATE/PRIOR_EVIDENCE.csv').open('w',newline='',encoding='utf-8') as f:
    keys=['method_family','prompt','exact_configuration','dataset','seeds','result','uncertainty','class_harm','evidence_status','limitation','may_reopen','required_new_hypothesis']
    w=csv.DictWriter(f,fieldnames=keys);w.writeheader()
    for family,prompt,config,status,limit,reopen,hyp in evidence:
        w.writerow(dict(method_family=family,prompt=prompt,exact_configuration=config,dataset='historical 450 enriched cohort' if prompt!='6' else 'amended preselection',seeds='17;29;43' if family in ['global-local','encoder adaptation'] else 'see canonical originating run configs',result='See originating raw epoch ledgers; no Exploration6 efficacy result',uncertainty='NOT RECORDED IN ORIGINAL RUN' if family=='augmentation' else 'see original artifacts',class_harm='No promotion inferred from mean alone',evidence_status=status,limitation=limit,may_reopen=reopen,required_new_hypothesis=hyp))
for src,dst in [('prompt6_fixed_suite.log','FULL_SUITE_POST_CV_FIX.log'),('prompt6_cv_regression.log','CV_FIX_REGRESSION.log'),('prompt6_post_preselect_suite.log','FULL_SUITE_PRE_CV_FIX.log'),('prompt6_preselect_help.log','preselect_prompt6_dataset_help.txt')]:shutil.copyfile(R/src,O/'PROVENANCE'/dst)
audit=json.loads((O/'PROVENANCE/CODEBASE_AUDIT.json').read_text());audit.update(tests_status='PASS',tests_count=78,tests_pass=78,tests_fail=0,tests_seconds=48.72,tests_log='FULL_SUITE_POST_CV_FIX.log',failed_tests=[],failure=None,source_matches_shipped_sha=False,deviations=['P6-P001 supplied preselection extension (4 files)','P6-P002 seeded CV group mapping compatibility; cv.py and new regression test'],original_certified_state='133/133 original SHA records matched before changes')
save('PROVENANCE/CODEBASE_AUDIT.json',audit)
with (O/'PROVENANCE/CODE_PATCH_LOG.md').open('a',encoding='utf-8') as f:f.write('\nP6-P001/P002 full-suite verification: **78 passed in 48.72s**. Targeted CV regression: **5 passed in 41.42s**. Original reference/certificate/hash files preserved.\n')
sources={str(p.relative_to(C)):sha(p) for folder in ['src','scripts','tests','configs','docs'] for p in (C/folder).rglob('*') if p.is_file() and '__pycache__' not in p.parts}
save('PROVENANCE/EXECUTED_CODE_HASHES.json',sources)
save('PROVENANCE/PROTOCOL_FREEZE.json',dict(utc=now,protocol_sha256=sha(O/'RESEARCH_STATE/PREREGISTERED_PROTOCOL.json'),amended_prompt_sha256=sha(O/'PROVENANCE/EXPLORATION6_AMENDED_INSTRUCTIONS.md'),code_manifest_sha256=sha(O/'PROVENANCE/EXECUTED_CODE_HASHES.json')))
print(json.dumps(dict(status='PREREGISTERED',configs=len(configs),utc=now)))
