import json,csv,collections,shutil
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
W=Path(__file__).resolve().parent;R=W.parents[1]/'outputs/STAGE2_RESEARCH_20260907';O=R/'90_comparative_analysis';A=R/'00_reference/biomask_audit';F=R/'92_figures/exploration3';F.mkdir(exist_ok=True)
def readcsv(p):return list(csv.DictReader(p.open()))
def table(h,rr):return '\n| '+' | '.join(h)+' |\n| '+' | '.join(['---']*len(h))+' |\n'+''.join('| '+' | '.join(str(x).replace('|','/') for x in r)+' |\n' for r in rr)+'\n'
def f(x):return f'{float(x):.5f}'
seed=readcsv(O/'architecture_seed_summary.csv');runs=readcsv(O/'architecture_stress_test.csv');pc=readcsv(O/'architecture_per_class.csv');conf=readcsv(O/'prompt3_confirmation.csv');final=json.loads((O/'prompt3_final_decision.json').read_text());quality=json.loads((A/'quality_summary.json').read_text());unc=json.loads((O/'architecture_paired_uncertainty.json').read_text());comp=json.loads((R/'91_error_analysis/exploration3/complementarity.json').read_text());gates=json.loads((R/'91_error_analysis/exploration3/gate_diagnostics.json').read_text())
plt.rcParams.update({'font.size':10,'axes.spines.top':False,'axes.spines.right':False})
real=[r for r in seed if r['control']=='real'];fig,ax=plt.subplots(figsize=(11,4));x=np.arange(len(real));ax.bar(x,[float(r['ROI_F1_mean']) for r in real],color=['#0072B2' if r['architecture'].startswith('A') else '#999999' for r in real]);ax.errorbar(x,[float(r['ROI_F1_mean']) for r in real],yerr=[float(r['ROI_F1_std']) for r in real],fmt='none',ecolor='black',capsize=3);ax.set_xticks(x,[r['architecture'] for r in real]);ax.set_ylabel('Combined OOF V17 ROI macro-F1');ax.set_title('Three-seed mean ± sample SD; gray BioMask models are contaminated diagnostics');fig.tight_layout();fig.savefig(F/'architecture_means.png',dpi=170,bbox_inches='tight');plt.close(fig)
fig,ax=plt.subplots(figsize=(8,4));rr=[r for r in seed if r['architecture'] in ['A1','A5']];ax.bar(range(len(rr)),[float(r['ROI_F1_mean']) for r in rr],color=['#0072B2','#777777','#D55E00','#999999']);ax.set_xticks(range(len(rr)),[r['architecture']+' '+r['control'] for r in rr]);ax.set_ylabel('Combined OOF V17 ROI macro-F1');ax.set_title('A5 must beat both capacity and shuffled-information controls');fig.tight_layout();fig.savefig(F/'A5_controls.png',dpi=170,bbox_inches='tight');plt.close(fig)
fig,ax=plt.subplots(figsize=(7,4));
for r in conf:ax.plot([0,1],[float(r['A1_final_epoch_ROI_F1']),float(r['A5_final_epoch_ROI_F1'])],marker='o',label='Seed '+r['seed'])
ax.set_xticks([0,1],['A1 preserved epoch10','A5 epoch10']);ax.set_ylabel('V17 ROI macro-F1');ax.set_title('Post-selection comparison on reused150 development cohort');ax.legend();fig.tight_layout();fig.savefig(F/'confirmation.png',dpi=170,bbox_inches='tight');plt.close(fig)
text='''# PUMA Stage 2 — integrated research report

## Architecture Stress Test and BioMask/Tier-B Investigation

**Exploration3 is complete. The single selected next full-data architecture is A5: frozen UNI2-h, FOV96, and a rank-eight multiplicative appearance ×16D Tier-A interaction added to linear appearance logits.** The encoder remains frozen. Trainable head parameters increase from15,530 (A1) to27,866 (A5). No BioMask, TierB, LoRA or additional gate enters the selected model.

This report extends the preserved Exploration2 record below; it does not restart the research. The previous30 runs and all caches remain intact. Exploration3 executed234 ten-epoch CV fits (26 predeclared real/control configurations ×3 seeds ×3 folds) and3 ten-epoch selected-candidate confirmation fits. These are237 fits, not237 distinct architectures. No further model family, rank16 search or hyperparameter grid was opened. Historical oracle results remain labeled historical and nondeployable.

### Previous conclusion / new evidence / updated conclusion

**Previous architecture conclusion:** A1, a linear Tier-A correction, was the best justified candidate among the Exploration2 controls. **New evidence:** A5 passed all prospective CV promotion tests and the fixed-final-epoch comparison against preserved A1 predictions. **Updated conclusion:** select A5 for exactly one next full-scale experiment. The previous report and A1 standalone source are archived unchanged under00_reference/PROMPT2_REPORT_PRESERVED.md and EXPLORATION2_STANDALONE. They are historical records, not competing current recommendations.

**Previous TierB conclusion:** no verified mask artifact had been established. **New evidence:** five historical final BioMask checkpoints and their fold/config metadata were recovered from Drive, and every checkpoint hash matched saved provenance. **Updated conclusion:** BioMask is available and can produce measurable masks, but its historical cross-fitting cannot support a clean current outer-validation estimate. B-series results are explicitly upstream-contaminated diagnostics and cannot justify promotion. High Dice does not repair that design issue.

### Architecture-selection protocol and validity

The existing300 training features were partitioned into3 ROI-disjoint StratifiedGroupKFold folds, random_state17. No additional expensive UNI2 extraction was needed. Each fold fits biology means/stds on its training rows only, and the same fold/seed uses the same replacement-balanced draw order across matched architectures. Every training fold includes all10 classes. Patient mapping is unverified; the saved historical case_id is just ROI ID. The existing150 cohort was withheld from internal architecture selection, although it had already influenced Exploration2 decisions.

All234 CV fits used frozen FOV96 CLS, nonaffine LayerNorm, ordinary CE, inverse-count sampling, AdamW LR.001 WD.01, batch64, gradient clip1, ten epochs and seeds17/29/43. The endpoint was **fixed epoch10**, not the best of ten validation epochs. Concatenate held-fold predictions for the300 features to compute exact V17 combined-OOF metrics; do not average semantic scores as if folds had equal size. The140-plus ROI grouping is the uncertainty unit, and different fitted models across folds are expected in cross-validation. Every per-fold metric, class count, confusion, exposure and gradient array is saved in the thin experiment directory.

Before new model outcomes, EXPLORATION3_PROTOCOL.md fixed the promotion conditions: ≥.003 mean ROI-F1 gain over A1, ≥2/3 positive seed deltas, ≥.002 superiority to each matched control, positive lower paired ROI-bootstrap interval endpoint, no class mean recall loss>.10, gap increase≤.05, plus a substantive gate spread for A3. These are pragmatic finite-study thresholds, not universal clinical significance criteria. No threshold was chosen after seeing a favorable architecture. A5 was the only passing model; rank8 was retained without a rank16 expansion.

### Confirmation protocol deviation

The selected candidate alone was fitted on the original300 training examples and compared with preserved A1 **final-epoch10** predictions on the original150. No A1 retraining, second-choice confirmation or best-epoch selection was performed. However, the generic training runner computed and logged intermediate validation metrics at all10 epochs instead of implementing the requested once-only evaluation interface. This is a protocol deviation. Only the predeclared final endpoint determined the decision, but the record must not be called a strictly blinded or untouched confirmation. Its uncertainty intervals are exploratory development intervals. Future locked full-data test evaluation must run only after all model choices are fixed.

### Exact evaluator parity and metric definitions

All Exploration2 V17 matcher/aggregator source remained byte-identical. Class-name conversion still maps canonical epithelium7/endothelium8 to local V17 IDs8/7. Strict radius<15, GT order, descending prediction score, stable distance ties and duplicate-centroid deletion behavior are preserved. Evaluation uses the existing component-aware GT centers, with prediction coordinates still the area-centroid crop points. This is a subset GT-point task, not all Stage1 proposals. Semantic accuracy is correctly classified annotation features / annotation features evaluated; it is not official PUMA accuracy. Classwise one-vs-rest accuracy is separately labeled in CSV and must not hide recall failure. ROI and pooled scores are both retained.

### Finite A-series and controls

A0 is the appearance-only1536→10 head. A1 adds zero-initialized biasless16→10 biology logits. A2 uses16→16 GELU→10 with the last layer zero initialized. A3 multiplies linear biology by10 sigmoid scalars. A4 multiplies it by sigmoid Linear2→1 of detached normalized appearance entropy and top1−top2 probability margin. A5 forms `(P_h h) elementwise*(P_b b)` with rank8 then a zero-initialized8→10 output, added to appearance logits. A6 replaces the head with1552→32 GELU→10.

For each A2–A6, a matched-capacity control replaces real biology with16 fixed tanh random-projected appearance features, and a shuffle control permutes training-row biology association only. Controls have the same architecture and parameter count. A6 cannot share the appearance-linear initialization because it replaces the head; its real/control bottlenecks are matched to each other. A3 is primarily a reparameterization of class-specific linear weights already expressible in A1, so gates alone cannot establish greater representational power. All additive/product residual output layers begin at zero, making initial predictions identical to their appearance head; projection gradients in A5 correctly begin at zero until the output matrix moves.

### BioMask architecture, checkpoints and fold audit

Direct folder fetches recovered binaries that Drive search omitted. The five final.pt files strict-loaded into the inspected model and matched saved SHA256 provenance. Saved epoch29 is epoch30 in human indexing; final checkpoints were used, not minimum held-loss checkpoints. Local V16.3.2/V17 BioMask inference ASTs agree; V16.3 differs. Complete source, metadata and checkpoint indexes are retained in biomask_audit.

The network accepts RGB plus a Gaussian point prompt, computes H/gradient internally, and uses a small GroupNorm/SiLU encoder-decoder with mask, prompt-conditioned presence, quality and center-offset outputs. Input crop96 uses historical reflect padding and valid masking. The weighted training objective combines mask BCE/Dice, empty-mask BCE, presence BCE, center smooth-L1 and quality BCE. No semantic GT class enters the forward input. See BIOMASK_AUDIT.md for exact channels, target/weight logic, loss coefficients and crop conventions.

Historical ROI fold counts are47,1,86,61,10; fold1 contains one ROI. The checkpoint for row-fold j excludes j but generally includes another outer-held fold k when it produces Stage2 training features. Every current held set spans multiple historical folds; none of the5 paths excludes all its outer groups. Using row-wise OOF outputs is therefore not nested cross-fitting. Additionally, upstream Stage1 OOF proposals used to train BioMask can carry outer information through other detector folds. No clean indirect independence is certified. We did not train20 nested models or silently exchange GT masks for predictions.

### Mask quality beyond segmentation loss

The five models were run once across the450 existing GT points, using their historical per-ROI fold, and cached. This is new GT-point inference, not the historical Stage1-proposal mask population. GT polygons were used only to measure quality; they never entered the predicted20D feature vectors. Binary quality uses threshold.5; soft-feature geometry retains historical formulas. Border and small/large strata, every ROI/class/fold, finite centroid counts and shape correlations are all reported. Empty masks have undefined centroid rather than artificial zero error.

### TierB feature families and downstream diagnostic scope

The unchanged historical20D extractor includes8 morphology quantities,6 mask-weighted H/gradient/texture quantities, ring contrast, mask maximum/mean and predicted quality, and2 ROI-relative proxies. Soft-mask axes/perimeter differ from binary regionprops quality measures; the entropy and percentile are historical proxies, not the TierA histogram entropy and empirical percentile. Exact schema and source hashes are preserved. Identity-token maps were discovered but excluded from these minimal models.

B0 tests TierB alone; B1 morphology; B2 weighted stain/texture; B3 fullB; B4 A+B. B3/B4 each have shuffledB and capacity-placeboB controls, with realA held constant in B4. B4's single zero-initialized biasless Linear36→10 is algebraically equivalent to the prescribed sum of separate16→10 and20→10 linear corrections under the same optimizer; its TierB correction norm is logged separately. All B runs carry upstream-contamination labels. The prior GT oracle is reused only as unmatched historical context, because its train/validation split differs from newCV. It remains nondeployable and is not a formal upper bound.

### Reviewer–architect conclusions

**A2 reviewer:** the tiny MLP may only add optimization noise. **Executed response:** it lost to A1 in meanCV; the extra282 parameters did not earn promotion. No hidden-width search followed.

**A3 reviewer:** class gates can reparameterize an already classwise linear correction and produce an interpretation story without predictive value. **Executed response:** gates had tiny within-fold class spreads (about.002–.005), failed the predeclared spread requirement, and supplied only a negligible average score change. Retain as a diagnostic, not a model component.

**A4 reviewer:** a gate correlated with uncertainty is not evidence it improves classification. **Executed response:** average gates remained approximately.514–.521 with within-fold standard deviations near.001. A3/A4 produced the same hard validation decisions in this screen. The small continuous-logit differences did not justify uncertainty gating.

**A5 reviewer:** a multiplicative residual can memorize the small cohort; its12,336 extra parameters need a control. **Executed response:** rank8 exceeded A1, the equal-capacity appearance placebo and shuffled biology across the aggregate CV comparisons, passed paired uncertainty and class/gap conditions, and improved the final endpoint in all3 confirmation seeds. This supports a conditional appearance/biology interaction within this study, not a proven causal biomarker. Rank16, LoRA and a larger branch were not tested or promoted.

**A6 reviewer:** a hidden head may improve simply by capacity. **Executed response:** the32-wide concat bottleneck did not meet the minimum gain/uncertainty criterion, despite some favorable class changes. Its50,026 parameters were not justified over A5 or A1.

**BioMask reviewer:** OOF labels and high Dice do not make the Stage2 evaluation clean. **Executed response:** agree. Quality was measured, fullB and A+B show modest diagnostic signals, but neither is promotion eligible. No segmentation-loss success claim was substituted for downstream validity. B0 is weak; B4 exceeds B3 only modestly. Additional mask inference/measurement complexity remains excluded from the selected architecture.

### Error complementarity and limitations

Disagreements are computed on combinedCV predictions for every real model with a positive mean delta. Counts pooled over3 seeds represent900 prediction-events on300 cells, not900 independent nuclei. QC examples are UID-ordered within each of four correctness categories; GT quality is diagnostic only. Mask quality/classification correlations are descriptive with repeated seed observations, not causal or significance tests. A good mask can be irrelevant to classification, and a poor mask can coincidentally change a decision favorably.

The full Stage1 proposal population, including missed/false proposals, has not been evaluated. ROI grouping is not verified patient grouping. Development reuse, small tail supports, only3 seeds, finite thresholds, uncertain acquisition confounding and the logged-intermediate-confirmation deviation remain material limitations. Neither the promoted A5 nor the historical BioMask has established clinical validity or SOTA.

### One next full-data experiment

Stop architecture expansion. Classify the complete fixed Stage1 proposal population using **A5 only**, seeds17/29/43 as independent repeats. Preserve coordinates, UIDs and detector metadata; do not change Stage1 thresholds, suppression or weights. Verify upstream out-of-fold training and all outer-group exclusions, use the highest genuinely verified patient/group unit, reserve natural calibration and a locked test, and retain zero-proposal ROIs and every FP/FN consequence in exact V17 evaluation. Unknown proposal semantics remain excluded only from semantic CE/conditional accuracy, not from PUMA counts. Do not add BioMask until a separate clean cross-fitting artifact establishes eligibility; that is not a second selected architecture.

Use the updated93_final_architecture package: FOV96→224 normalized RGB; frozen UNI2 CLS1536 with nonaffine LayerNorm; train-standardized16D TierA; biasless1536→8 and16→8 projections, elementwise product and zero-initialized8→10 correction; appearance1536→10 linear head. Balanced sampling and ordinary CE, AdamW.001/WD.01, batch64/clip1. The full-data maximum20 epochs/patience5 remains a prospective schedule, distinct from fixed10 architecture endpoints. Optional scalarT calibration uses a separate natural cohort and requires re-evaluation of confidence-based matching. There is no backbone adaptation, mask branch or gate.

'''
text+='### Seed-aggregated comparison\n'+table(['Architecture','Control','Params','ROI F1 mean','SD','Delta vs A1','95% ROI delta interval','Semantic F1','Accuracy','Decision'],[[r['architecture'],r['control'],r['parameters'],f(r['ROI_F1_mean']),f(r['ROI_F1_std']),f(r['paired_delta_vs_A1']),f(r['roi_bootstrap_low'])+' to '+f(r['roi_bootstrap_high']),f(r['semantic_f1_mean']),f(r['Accuracy_mean']),r['decision']] for r in seed])
text+='\n![Architecture summary](92_figures/exploration3/architecture_means.png)\n\n![A5 controls](92_figures/exploration3/A5_controls.png)\n'
text+='### Final-epoch confirmation\n'+table(['Seed','A1 ROI F1','A5 ROI F1','Delta','A1 semantic F1','A5 semantic F1','A1 accuracy','A5 accuracy'],[[r['seed'],*[f(r[k]) for k in ['A1_final_epoch_ROI_F1','A5_final_epoch_ROI_F1','delta','A1_semantic_F1','A5_semantic_F1','A1_accuracy','A5_accuracy']]] for r in conf])
text+='\nMean paired delta '+f(final['mean_delta'])+'; exploratory40-ROI bootstrap95% interval '+str(final['roi_bootstrap_95'])+'. No comparison uses A1’s earlier best checkpoint as a mismatched endpoint.\n\n![Confirmation](92_figures/exploration3/confirmation.png)\n'
text+='### BioMask measured quality\n'+table(['Measurement','Mean','Median','Finite n'],[[k,f(quality['overall'][k+'_mean']),f(quality['overall'][k+'_median']),quality['overall'][k+'_finite_n']] for k in ['dice','iou','area_relative_error','centroid_error','occupancy','quality_confidence']])
text+=table(['Morphology','Prediction–GT Pearson r'],[[k,f(quality['overall'][k+'_pearson'])] for k in ['area','major','minor','eccentricity','perimeter','circularity']]);text+='\nPredicted quality versus IoU Pearson r='+f(quality['overall']['confidence_vs_iou_pearson'])+'. These diagnostics include450 GT-point cases and cannot certify clean outer generalization.\n\n![Mask QC](00_reference/biomask_audit/qc/quality_examples_1.png)\n'
text+='### Complementarity (900 seed-events; not independent observations)\n'+table(['Model','A1 wrong→correct','A1 correct→wrong','Both wrong','Both correct','Dice vs delta r','Correction norm vs delta r'],[[k,v['counts'].get('A1_wrong_candidate_correct',0),v['counts'].get('A1_correct_candidate_wrong',0),v['counts'].get('both_wrong',0),v['counts'].get('both_correct',0),f(v['dice_vs_delta']) if v['dice_vs_delta'] is not None else 'NA',f(v['correction_norm_vs_delta']) if v['correction_norm_vs_delta'] is not None else 'NA'] for k,v in comp.items()])
text+='\nB3/B4 Dice-to-classification-delta correlations are weakly negative in these contaminated diagnostics. Better Dice did not imply larger downstream gain. Good/poor-mask contingency tables and morphology-error correlations are in91_error_analysis/exploration3/complementarity.json.\n'
classes=list(dict.fromkeys(r['class'] for r in pc));text+='### Per-class combinedCV means for each real architecture\n\nP/R/F1 are conditional semantic metrics here; the accompanying CSV supplies every seed’s exact V17 pooled and ROI P/R/F1, TP/FP/FN, dominant errors, support and positive-ROI count. One-vs-rest accuracy is separately named and does not replace recall.\n'
for model in [r['architecture'] for r in real]:
    text+='\n#### '+model+'\n';cr=[]
    for c in classes:
        rs=[r for r in pc if r['architecture']==model and r['control']=='real' and r['class']==c];cr.append([c,rs[0]['support'],rs[0]['positive_ROIs'],*[f(np.mean([float(r[k]) for r in rs])) for k in ['semantic_P','semantic_R','semantic_F1','one_vs_rest_accuracy','recall_delta_vs_A1','ROI_P','ROI_R','ROI_F1']]])
    text+=table(['Class','n','Positive ROIs','Semantic P','R','F1','OvR acc','Δ recall vs A1','ROI P','R','F1'],cr)
text+='### Complete per-fit ledger\n\nEach row is a10-epoch fit with fixed final checkpoint. Full epoch histories, confusion matrices, prevalence and per-ROI counts remain in its linked directory; all per-class numerical arrays are preserved rather than rounded away.\n'
text+=table(['Fit','Params','ROI P','R','F1','Pooled P','R','F1','Accuracy','BA','NLL','ECE','Gap','Seconds'],[[r['ID'],r['parameters'],*[f(r[k]) for k in ['ROI_precision','ROI_recall','ROI_f1','pooled_precision','pooled_recall','pooled_f1','Accuracy','BalancedAccuracy','NLL','ECE15','gap','runtime_seconds']]] for r in runs])
elapsed=sum(float(r['runtime_seconds']) for r in runs);extract=json.loads((R/'02_cache/biomask/prompt3_gt_diagnostic/complete.json').read_text())
text+=f'\n### Compute and verification\n\nThe234 CV fits took {elapsed:.2f} cumulative measured training/evaluation seconds, excluding orchestration/imports and the3 confirmation fits. One-time BioMask450-point extraction took {extract["seconds"]:.2f} seconds on CPU and strict-loaded all5 checkpoints. UNI2/TierA caches were reused; no encoder training or new full-image cache was needed. All source-hash checks and standalone verification results are in93_final_architecture/VERIFICATION.json. The updated A5 head reproduces executed confirmation logits within floating-point tolerance; this is implementation parity, not an external performance test.\n'
text+='\n### Deliverable map and completion\n\n[BioMask audit](00_reference/biomask_audit/BIOMASK_AUDIT.md), [fold provenance](00_reference/biomask_audit/fold_provenance.csv), [mask quality](00_reference/biomask_audit/quality_grouped.csv), [TierB schema](02_cache/biology/tierB_schema.json), [architecture fits](90_comparative_analysis/architecture_stress_test.csv), [seed summary](90_comparative_analysis/architecture_seed_summary.csv), [per-class metrics](90_comparative_analysis/architecture_per_class.csv), [confirmation classes](90_comparative_analysis/prompt3_confirmation_per_class.csv), [paired uncertainty](90_comparative_analysis/architecture_paired_uncertainty.json), [final implementation](93_final_architecture/README.md). Exploration3’s finite tests, controls, artifact audit, quality analysis and final selection are complete. Stage1/full-data clinical and SOTA validation are not claimed.\n'
text+='\n---\n\n# Preserved Exploration2 integrated record — historical conclusions below\n\nThe following record is preserved to avoid silently erasing earlier conclusions. Its A1 recommendation was current at Exploration2 completion; the A5 decision above is the single current recommendation. Original experiment results remain valid within their stated scope.\n\n'+(R/'00_reference/PROMPT2_REPORT_PRESERVED.md').read_text(encoding='utf-8')
(R/'STAGE2_RESEARCH_REPORT.md').write_text(text,encoding='utf-8')
repro=R/'00_reference/prompt3_reproduction';repro.mkdir(exist_ok=True)
for p in W.glob('*.py'):shutil.copy2(p,repro/p.name)
state=json.loads((R/'00_reference/RESEARCH_STATE.json').read_text());state.update(status='complete',phase='Exploration3 finite architecture/BioMask investigation complete',selected_architecture='A5 frozen UNI2 FOV96 rank8 appearance x TierA interaction, 27866 trainable parameters',next=['One full-data fixed-Stage1 proposal population experiment with A5; verify outer-group provenance and locked evaluation']);state['exploration3'].update(completed_cv_fits=234,confirmation_fits=3,selected='A5',BioMask='recovered quality quantified; downstream upstream-contaminated, excluded',final_decision=final);(R/'00_reference/RESEARCH_STATE.json').write_text(json.dumps(state,indent=2))
(R/'README.md').write_text('''# PUMA Stage2 — Exploration3 complete

Read [STAGE2_RESEARCH_REPORT.md](STAGE2_RESEARCH_REPORT.md). Current selection: **A5 frozen UNI2-h / FOV96 / rank8 appearance×16D TierA interaction / balanced CE**,27,866 trainable parameters. No BioMask or LoRA in the selected architecture.

Exploration3 completed234 grouped-CV fits plus3 selected-candidate fits; Exploration2’s30 runs remain intact. BioMask checkpoints and masks were recovered and measured, but historical outer contamination prevents clean TierB promotion. All results are development/GT-point evidence, not full Stage1 population or SOTA validation.

The standalone current code is93_final_architecture. Prior A1 code/report are archived under00_reference/EXPLORATION2_STANDALONE and PROMPT2_REPORT_PRESERVED.md. New architecture metrics are in90_comparative_analysis, mask audit in00_reference/biomask_audit, and new disagreement analysis in91_error_analysis/exploration3. Source modules used for older runs remain unchanged. New exploration3 modules are shared and config-driven.

Archive source scripts in00_reference/prompt3_reproduction assume their original work/exploration3 layout; use93_final_architecture for standalone execution. External original image/annotation paths and UNI2 weights remain read-only dependencies. ARTIFACT_SHA256.csv records bundled file hashes. The once-only confirmation-interface deviation is explicitly documented in the report; only fixed epoch10 drove the comparison.
''',encoding='utf-8');print('Report chars',len(text),'CV compute seconds',elapsed)
